// eslint-disable-next-line import/no-unassigned-import
import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Fab } from '@/components/home/Fab';
import { NavBar } from '@/components/NavBar';
import { injectThemeVariables } from '@/theme';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<style suppressHydrationWarning>{injectThemeVariables()}</style>
				<NavBar />
				{children}
				<Fab />
			</body>
		</html>
	);
}
